### PR TITLE
Pumpkin haver

### PR DESCRIPTION
**Pull request by BigK-hub**
I added fs dithering and merged current state of main with it.

### CODE REVIEW

**Review by domjanabi — CHANGES_REQUESTED** [review]
I think it should be renamed to FloydSteinbergDithering, even if it's a bit long. It's not like anyone besides us will have to spell it out.

**Comment by BigK-hub** [comment]
After alot of work and sweat I managed to scatter thru endless reasearch papers. I finally managed to commit the changes u requested. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

**Review by domjanabi — APPROVED** [review]
bien👍

**Review by domjanabi — APPROVED** [review]
beyond pleased with this wondrous pull request

**Pull request merged**
